base.url=http://the-internet.herokuapp.com

browser=chrome
headless=true

implicit.wait=10
explicit.wait=15
page.load.timeout=20

thread.count=4

screenshot.on.failure=true
screenshot.path=target/screenshots/

log.level=INFO
log.path=target/logs/
